---
language: node_js
node_js:
  - "8"
notifications:
  email: false
cache: npm
before_install:
  - cd df-webhook
install:
  - npm install
script:
  - npm test
  - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coverage
