language: node_js
node_js:
- '10'
notifications:
  email: false
cache: npm
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GCP_PROJECT_ID=export-df-logs-to-bq
  - LOCATION_ID=asia-south1
  - QUEUE_ID=conversations
  - secure: P9sIddtEctPfGm5JUDhgoHKUIqyfemP71DUJ/CTXZCLR4rV3c9mfjOqwdBDNL6K+ZE1a1SzEZ03uonLPR6FMAqshBpo/TI5De315vIhTKSy+zXo/yq+NAEf9Jukg5YvmjBey6VNY0PX3yJbE+mT8S1zy51KaFka7miSAdAQ4dYn9bg+67jXFZx3AV0YMvtAcBtzhFWRQ4mxbK0YN0l4fTbyyAr//3z1+Tqejii3OHPIfXsoUuXY8dlGIRL/SWWaGRQNYDMNL22vAdtKLb4tmvC2/Db9y7Rc6ec7GsB75cVcc2j1nlhV1YAl8gAU0DIJI5lJsVQoFcGvehqJPY4ia2woEUzBlIUMtVl72VzbVgqW733KaRu08SoaNX7slCtfdxSfJnQo1bH7JWYbmb1d4aemSeeep9y1PSpi4KEWSjZ4E33PnsXR5E41uLrQARwDTlPj69H3pWp3roTCY7G0F98uLzgXzIVeYcmWWiFUDYBGXQw1dGjjZa0wSHeIgo2z4lVQrlB1iDffjTk1NSd9l/rDpTHHNv9k+nW7xbBNVlcIifvHDfT2REce4/ec6t4TeudzzkstizliGN6Wknklot50hXq5Na5c+iyYAM/rAqsydVz9O/8484Mo0Dgq80Aid4o0GBoTjIrZQZMNTbxtaCv9I6ZEqwyBgL9TbmAsx5ZM=
before_install:
# Create App Engine Queue
- cd cloud-tasks
- openssl aes-256-cbc -K $encrypted_53504847729c_key -iv $encrypted_53504847729c_iv
  -in gcp-sa-tasks-creds.json.enc -out gcp-sa-tasks-creds.json -d
- npm install
- GOOGLE_APPLICATION_CREDENTIALS=gcp-sa-tasks-creds.json PROJECT_ID=$PROJECT_ID LOCATION_ID=$LOCATION_ID QUEUE_ID=$QUEUE_ID npm start
# Deploy webhook
- cd ../df-webhook
- openssl aes-256-cbc -K $encrypted_53504847729c_key -iv $encrypted_53504847729c_iv
  -in gcp-sa-creds.json.enc -out gcp-sa-creds.json -d
install:
- npm install
script:
- npm test
- COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coverage
deploy:
  provider: gae
  keyfile: gcp-sa-creds.json
  project: export-df-logs-to-bq
  default: true
