runtime: nodejs10

# Provide a service name if this is not your first GAE service
# service: df-webhook

# Ensure that app is always served on https
# i.e redirect all http requests to https
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_vars:
  - TOPIC_NAME: conversations

instance_class: F1
automatic_scaling:
  max_instances: 10
  max_concurrent_requests: 25
  target_cpu_utilization: 0.7
